GRANT ALL ON SEQUENCE annotation_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_agent_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_agent_email_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_agent_email_sha1_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_agent_homepage_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_agent_name_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_agent_type_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_body_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_collection_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_history_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_selector_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_target_id_seq TO annotations_role;
GRANT ALL ON SEQUENCE annotation_temporal_id_seq TO annotations_role;

GRANT EXECUTE ON FUNCTION public.annotation_body_create(integer, character varying, character varying, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_data_position_selector_create(integer, integer, character varying, integer, integer, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_svg_selector_delete(integer, integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_delete(character varying, character varying) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_target_delete(integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_generator_delete(integer, integer, integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_creator(boolean, boolean, boolean, character varying, character varying, boolean) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_temporal_create(integer, integer, integer, character varying, timestamp without time zone, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_text_quote_selector_delete(integer, integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_body_delete(integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_creator_delete(integer, integer, integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_target(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_xpath_selector_create(integer, integer, character varying, text, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_temporal(boolean, boolean, boolean, character varying[], timestamp without time zone) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_css_selector_create(integer, integer, character varying, text, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_text_position_selector_delete(integer, integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_history_delete(integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_fragment_selector_create(integer, integer, character varying, text, text, integer, integer, integer, integer, integer, integer, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_update(character varying, character varying, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_creator_create(integer, integer, integer, character varying, jsonb, character varying[], jsonb[], text[], jsonb[], character varying, text[], jsonb[], text[], jsonb[], text[], jsonb[]) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_xpath_selector_delete(integer, integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_history_create(integer, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_text_position_selector_create(integer, integer, character varying, integer, integer, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_css_selector_delete(integer, integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_fragment_selector_delete(integer, integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_collection_create(character varying, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_data_position_selector_delete(integer, integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_svg_selector_create(integer, integer, character varying, text, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_create(character varying, character varying, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_target_create(integer, character varying, character varying, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_generator_create(integer, integer, integer, character varying, jsonb, character varying[], jsonb[], text[], jsonb[], character varying, text[], jsonb[], text[], jsonb[], text[], jsonb[]) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_generator(boolean, boolean, boolean, character varying, character varying, boolean) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_temporal_delete(integer, integer, integer) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_text_quote_selector_create(integer, integer, character varying, text, text, text, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_target(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_temporal(boolean, boolean, boolean, character varying[], timestamp without time zone) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_creator(boolean, boolean, boolean, character varying, character varying, boolean) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_delete(character varying, character varying) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_update(character varying, character varying, jsonb) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) TO annotations_role;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_generator(boolean, boolean, boolean, character varying, character varying, boolean) TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_body TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_agent_type TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_selector TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_agent_email_sha1 TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_collection TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_temporal TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_agent_email TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_history TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_agent_homepage TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_target TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_agent TO annotations_role;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.annotation_agent_name TO annotations_role;
GRANT ALL ON TABLE public.annotation_history_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_body_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_css_selector_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_fragment_selector_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_collection_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_xpath_selector_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_generator_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_svg_selector_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_temporal_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_data_position_selector_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_target_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_creator_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_text_quote_selector_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_text_position_selector_get TO annotations_role;
GRANT ALL ON TABLE public.annotation_get TO annotations_role;
