ALTER FUNCTION public.annotation_body_create(integer, character varying, character varying, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_body_create(integer, character varying, character varying, jsonb) TO postgres;
ALTER FUNCTION public.annotation_data_position_selector_create(integer, integer, character varying, integer, integer, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_data_position_selector_create(integer, integer, character varying, integer, integer, jsonb) TO postgres;
ALTER FUNCTION public.annotation_svg_selector_delete(integer, integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_svg_selector_delete(integer, integer) TO postgres;
ALTER FUNCTION public.annotation_delete(character varying, character varying) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_delete(character varying, character varying) TO postgres;
ALTER FUNCTION public.annotation_target_delete(integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_target_delete(integer) TO postgres;
ALTER FUNCTION public.annotation_generator_delete(integer, integer, integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_generator_delete(integer, integer, integer) TO postgres;
ALTER FUNCTION public.annotation_search_by_creator(boolean, boolean, boolean, character varying, character varying, boolean) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_creator(boolean, boolean, boolean, character varying, character varying, boolean) TO postgres;
ALTER FUNCTION public.annotation_temporal_create(integer, integer, integer, character varying, timestamp without time zone, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_temporal_create(integer, integer, integer, character varying, timestamp without time zone, jsonb) TO postgres;
ALTER FUNCTION public.annotation_text_quote_selector_delete(integer, integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_text_quote_selector_delete(integer, integer) TO postgres;
ALTER FUNCTION public.annotation_body_delete(integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_body_delete(integer) TO postgres;
ALTER FUNCTION public.annotation_creator_delete(integer, integer, integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_creator_delete(integer, integer, integer) TO postgres;
ALTER FUNCTION public.annotation_search_by_target(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_target(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) TO postgres;
ALTER FUNCTION public.annotation_xpath_selector_create(integer, integer, character varying, text, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_xpath_selector_create(integer, integer, character varying, text, jsonb) TO postgres;
ALTER FUNCTION public.annotation_search_by_temporal(boolean, boolean, boolean, character varying[], timestamp without time zone) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_temporal(boolean, boolean, boolean, character varying[], timestamp without time zone) TO postgres;
ALTER FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) TO postgres;
ALTER FUNCTION public.annotation_css_selector_create(integer, integer, character varying, text, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_css_selector_create(integer, integer, character varying, text, jsonb) TO postgres;
ALTER FUNCTION public.annotation_text_position_selector_delete(integer, integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_text_position_selector_delete(integer, integer) TO postgres;
ALTER FUNCTION public.annotation_history_delete(integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_history_delete(integer) TO postgres;
ALTER FUNCTION public.annotation_fragment_selector_create(integer, integer, character varying, text, text, integer, integer, integer, integer, integer, integer, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_fragment_selector_create(integer, integer, character varying, text, text, integer, integer, integer, integer, integer, integer, jsonb) TO postgres;
ALTER FUNCTION public.annotation_update(character varying, character varying, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_update(character varying, character varying, jsonb) TO postgres;
ALTER FUNCTION public.annotation_creator_create(integer, integer, integer, character varying, jsonb, character varying[], jsonb[], text[], jsonb[], character varying, text[], jsonb[], text[], jsonb[], text[], jsonb[]) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_creator_create(integer, integer, integer, character varying, jsonb, character varying[], jsonb[], text[], jsonb[], character varying, text[], jsonb[], text[], jsonb[], text[], jsonb[]) TO postgres;
ALTER FUNCTION public.annotation_xpath_selector_delete(integer, integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_xpath_selector_delete(integer, integer) TO postgres;
ALTER FUNCTION public.annotation_history_create(integer, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_history_create(integer, jsonb) TO postgres;
ALTER FUNCTION public.annotation_text_position_selector_create(integer, integer, character varying, integer, integer, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_text_position_selector_create(integer, integer, character varying, integer, integer, jsonb) TO postgres;
ALTER FUNCTION public.annotation_css_selector_delete(integer, integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_css_selector_delete(integer, integer) TO postgres;
ALTER FUNCTION public.annotation_fragment_selector_delete(integer, integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_fragment_selector_delete(integer, integer) TO postgres;
ALTER FUNCTION public.annotation_collection_create(character varying, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_collection_create(character varying, jsonb) TO postgres;
ALTER FUNCTION public.annotation_data_position_selector_delete(integer, integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_data_position_selector_delete(integer, integer) TO postgres;
ALTER FUNCTION public.annotation_svg_selector_create(integer, integer, character varying, text, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_svg_selector_create(integer, integer, character varying, text, jsonb) TO postgres;
ALTER FUNCTION public.annotation_create(character varying, character varying, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_create(character varying, character varying, jsonb) TO postgres;
ALTER FUNCTION public.annotation_target_create(integer, character varying, character varying, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_target_create(integer, character varying, character varying, jsonb) TO postgres;
ALTER FUNCTION public.annotation_generator_create(integer, integer, integer, character varying, jsonb, character varying[], jsonb[], text[], jsonb[], character varying, text[], jsonb[], text[], jsonb[], text[], jsonb[]) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_generator_create(integer, integer, integer, character varying, jsonb, character varying[], jsonb[], text[], jsonb[], character varying, text[], jsonb[], text[], jsonb[], text[], jsonb[]) TO postgres;
ALTER FUNCTION public.annotation_search_by_generator(boolean, boolean, boolean, character varying, character varying, boolean) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_generator(boolean, boolean, boolean, character varying, character varying, boolean) TO postgres;
ALTER FUNCTION public.annotation_temporal_delete(integer, integer, integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_temporal_delete(integer, integer, integer) TO postgres;
ALTER FUNCTION public.annotation_text_quote_selector_create(integer, integer, character varying, text, text, text, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_text_quote_selector_create(integer, integer, character varying, text, text, text, jsonb) TO postgres;
ALTER FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) TO postgres;
ALTER FUNCTION public.annotation_search_by_target(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_target(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) TO postgres;
ALTER FUNCTION public.annotation_search_by_temporal(boolean, boolean, boolean, character varying[], timestamp without time zone) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_temporal(boolean, boolean, boolean, character varying[], timestamp without time zone) TO postgres;
ALTER FUNCTION public.annotation_search_by_creator(boolean, boolean, boolean, character varying, character varying, boolean) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_creator(boolean, boolean, boolean, character varying, character varying, boolean) TO postgres;
ALTER FUNCTION public.annotation_delete(character varying, character varying) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_delete(character varying, character varying) TO postgres;
ALTER FUNCTION public.annotation_update(character varying, character varying, jsonb) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_update(character varying, character varying, jsonb) TO postgres;
ALTER FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) TO postgres;
ALTER FUNCTION public.annotation_search_by_generator(boolean, boolean, boolean, character varying, character varying, boolean) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.annotation_search_by_generator(boolean, boolean, boolean, character varying, character varying, boolean) TO postgres;
ALTER TABLE public.annotation_body OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_body TO postgres;
ALTER TABLE public.annotation OWNER TO postgres;
GRANT ALL ON TABLE public.annotation TO postgres;
ALTER TABLE public.annotation_agent_type OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_agent_type TO postgres;
ALTER TABLE public.annotation_selector OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_selector TO postgres;
ALTER TABLE public.annotation_agent_email_sha1 OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_agent_email_sha1 TO postgres;
ALTER TABLE public.annotation_collection OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_collection TO postgres;
ALTER TABLE public.annotation_temporal OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_temporal TO postgres;
ALTER TABLE public.annotation_agent_email OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_agent_email TO postgres;
ALTER TABLE public.annotation_history OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_history TO postgres;
ALTER TABLE public.annotation_agent_homepage OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_agent_homepage TO postgres;
ALTER TABLE public.annotation_target OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_target TO postgres;
ALTER TABLE public.annotation_agent OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_agent TO postgres;
ALTER TABLE public.annotation_agent_name OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_agent_name TO postgres;
ALTER TABLE public.annotation_history_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_history_get TO postgres;
ALTER TABLE public.annotation_body_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_body_get TO postgres;
ALTER TABLE public.annotation_css_selector_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_css_selector_get TO postgres;
ALTER TABLE public.annotation_fragment_selector_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_fragment_selector_get TO postgres;
ALTER TABLE public.annotation_collection_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_collection_get TO postgres;
ALTER TABLE public.annotation_xpath_selector_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_xpath_selector_get TO postgres;
ALTER TABLE public.annotation_generator_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_generator_get TO postgres;
ALTER TABLE public.annotation_svg_selector_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_svg_selector_get TO postgres;
ALTER TABLE public.annotation_temporal_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_temporal_get TO postgres;
ALTER TABLE public.annotation_data_position_selector_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_data_position_selector_get TO postgres;
ALTER TABLE public.annotation_target_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_target_get TO postgres;
ALTER TABLE public.annotation_creator_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_creator_get TO postgres;
ALTER TABLE public.annotation_text_quote_selector_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_text_quote_selector_get TO postgres;
ALTER TABLE public.annotation_text_position_selector_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_text_position_selector_get TO postgres;
ALTER TABLE public.annotation_get OWNER TO postgres;
GRANT ALL ON TABLE public.annotation_get TO postgres;
