REVOKE ALL ON FUNCTION public.annotation_body_create(integer, character varying, character varying, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_data_position_selector_create(integer, integer, character varying, integer, integer, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_svg_selector_delete(integer, integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_delete(character varying, character varying) FROM public;
REVOKE ALL ON FUNCTION public.annotation_target_delete(integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_generator_delete(integer, integer, integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_search_by_creator(boolean, boolean, boolean, character varying, character varying, boolean) FROM public;
REVOKE ALL ON FUNCTION public.annotation_temporal_create(integer, integer, integer, character varying, timestamp without time zone, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_text_quote_selector_delete(integer, integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_body_delete(integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_creator_delete(integer, integer, integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_search_by_target(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) FROM public;
REVOKE ALL ON FUNCTION public.annotation_xpath_selector_create(integer, integer, character varying, text, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_search_by_temporal(boolean, boolean, boolean, character varying[], timestamp without time zone) FROM public;
REVOKE ALL ON FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) FROM public;
REVOKE ALL ON FUNCTION public.annotation_css_selector_create(integer, integer, character varying, text, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_text_position_selector_delete(integer, integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_history_delete(integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_fragment_selector_create(integer, integer, character varying, text, text, integer, integer, integer, integer, integer, integer, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_update(character varying, character varying, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_creator_create(integer, integer, integer, character varying, jsonb, character varying[], jsonb[], text[], jsonb[], character varying, text[], jsonb[], text[], jsonb[], text[], jsonb[]) FROM public;
REVOKE ALL ON FUNCTION public.annotation_xpath_selector_delete(integer, integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_history_create(integer, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_text_position_selector_create(integer, integer, character varying, integer, integer, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_css_selector_delete(integer, integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_fragment_selector_delete(integer, integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_collection_create(character varying, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_data_position_selector_delete(integer, integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_svg_selector_create(integer, integer, character varying, text, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_create(character varying, character varying, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_target_create(integer, character varying, character varying, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_generator_create(integer, integer, integer, character varying, jsonb, character varying[], jsonb[], text[], jsonb[], character varying, text[], jsonb[], text[], jsonb[], text[], jsonb[]) FROM public;
REVOKE ALL ON FUNCTION public.annotation_search_by_generator(boolean, boolean, boolean, character varying, character varying, boolean) FROM public;
REVOKE ALL ON FUNCTION public.annotation_temporal_delete(integer, integer, integer) FROM public;
REVOKE ALL ON FUNCTION public.annotation_text_quote_selector_create(integer, integer, character varying, text, text, text, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) FROM public;
REVOKE ALL ON FUNCTION public.annotation_search_by_target(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) FROM public;
REVOKE ALL ON FUNCTION public.annotation_search_by_temporal(boolean, boolean, boolean, character varying[], timestamp without time zone) FROM public;
REVOKE ALL ON FUNCTION public.annotation_search_by_creator(boolean, boolean, boolean, character varying, character varying, boolean) FROM public;
REVOKE ALL ON FUNCTION public.annotation_delete(character varying, character varying) FROM public;
REVOKE ALL ON FUNCTION public.annotation_update(character varying, character varying, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.annotation_search_by_body(boolean, boolean, character varying, boolean, integer, integer, integer, integer, integer, integer, character varying, character varying) FROM public;
REVOKE ALL ON FUNCTION public.annotation_search_by_generator(boolean, boolean, boolean, character varying, character varying, boolean) FROM public;
